// code/sample.svelte
<script>
    import { writable } from 'svelte/store';
  
    // Create a writable store to manage state
    let name = writable('Alice');
    let numbers = writable([1, 2, 3]);
  
    function greet() {
      // Access the store value using $ prefix
      console.log(`Hello, ${$name}!`);
    }
  
    function addNumber() {
      // Update the store value
      numbers.update(n => [...n, n.length + 1]);
    }
</script>
  
<main>
  <h1>Hello World</h1>
  <button on:click={greet}>Greet</button>
  <button on:click={addNumber}>Add Number</button>
  <ul>
    {#each $numbers as n}
      <li>Number: {n}</li>
    {/each}
  </ul>
</main>

<style>
  h1 {
    color: #ff3e00;
  }

  button {
    margin-right: 10px;
  }
</style>

// code/sample.vue
<template>
    <div id="app">
        <h1>{{ title }}</h1>
        <button @click="greet">Greet</button>
        <ul>
            <li v-for="n in numbers" :key="n">Number: {{ n }}</li>
        </ul>
    </div>
</template>

<script>
export default {
    data() {
        return {
            title: 'Hello World',
            name: 'Alice',
            numbers: [1, 2, 3],
        };
    },
    methods: {
        greet() {
            console.log(`Hello, ${this.name}!`);
        }
    }
};
</script>

<style scoped>
h1 {
    color: #42b983;
}
</style>
